language: node_js
node_js:
  - 12

services:
  - docker

install:
  - echo "install nothing"

before_script:
  - echo "no tests"

script:
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed saltfpt/udagram-api-feed:v1
  - docker tag udagram-api-user saltfpt/udagram-api-user:v1
  - docker tag reverseproxy saltfpt/reverseproxy:v1
  - docker tag udagram-frontend saltfpt/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push saltfpt/udagram-api-feed:v1
  - docker push saltfpt/udagram-api-user:v1
  - docker push saltfpt/reverseproxy:v1
  - docker push saltfpt/udagram-frontend:v1
