version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:16
    steps:
      - checkout

  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservice
          command: |
            echo "--- Installing dependencies ---"
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node -v
            npm -v
            echo "--- Building images ---"
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed produc/udagram-api-feed:v1
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user produc/udagram-api-user:v1
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend produc/udagram-frontend:v8
            docker build -t reverseproxy ./udagram-reverseproxy
            docker tag reverseproxy produc/reverseproxy:v1
            echo "--- All images successfully built ---"
            echo "--- Logging in to Docker Hub ---"
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            echo "--- Pushing images to Docker Hub ---"
            docker push produc/udagram-api-feed:v1
            docker push produc/udagram-api-user:v1
            docker push produc/udagram-frontend:v8
            docker push produc/reverseproxy:v1

workflows:
  version: 2
  default:
    jobs:
      - lint-app
      - build-docker:
          requires:
            - lint-app
