version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  build:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker images
          command: |
            docker-compose -f docker-compose-build.yaml build --parallel
      - run:
          name: Tag Docker images
          command: |
            docker tag udagram-api-feed produc/udagram-api-feed:v1
            docker tag udagram-api-user produc/udagram-api-user:v1
            docker tag reverseproxy produc/reverseproxy:v1
            docker tag udagram-frontend produc/udagram-frontend:v2

  push_to_docker_hub:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Push Docker images to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push produc/udagram-api-feed:v1
            docker push produc/udagram-api-user:v1
            docker push produc/reverseproxy:v1
            docker push produc/udagram-frontend:v2

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - push_to_docker_hub:
          requires:
            - build